using Dapper.CodeAnalysis;
using System.Threading.Tasks;
using Xunit;
using Diagnostics = Dapper.CodeAnalysis.DapperAnalyzer.Diagnostics;
namespace Dapper.AOT.Test.Verifiers;

public class DAP214 : Verifier<DapperAnalyzer>
{
    [Fact]
    public Task VariableNotDeclared() => SqlVerifyAsync("""
        select {|#0:@i|};
        """, SqlAnalysis.SqlParseInputFlags.KnownParameters, Diagnostic(Diagnostics.VariableNotDeclared).WithLocation(0).WithArguments("@i"));

    private const string SqlClass = """
        static class Sql
        {
            public const string GetUsers =
                "select Id from Users where LoginCount >= {|#2:@MinLogins|}";
        }
        """;

    // same class behind an <auto-generated> header, as a source generator would emit
    private const string GeneratedSqlClass = "// <auto-generated/>\n" + SqlClass;

    [Fact] // const sql in a generated doc re-homes to the call-site, https://github.com/DapperLib/DapperAOT/issues/177
    public Task ConstSqlInGeneratedDocument() => CSVerifyAsync(""""
        using Dapper;
        using System.Data.Common;

        [DapperAot]
        static class Q
        {
            public static void ViaConst(DbConnection c) =>
                c.Query<int>({|#0:Sql.GetUsers|}, {|#1:new { Wrong = 1 }|});
        }
        """", DefaultConfig, [
            Diagnostic(Diagnostics.VariableNotDeclared).WithLocation(0).WithArguments("@MinLogins"),
            Diagnostic(Diagnostics.SqlParametersNotDetected).WithLocation(1),
    ], additionalSources: [GeneratedSqlClass]);

    [Fact] // const sql in a visible sibling doc keeps its declaration token, https://github.com/DapperLib/DapperAOT/issues/177
    public Task ConstSqlInVisibleSiblingDocument() => CSVerifyAsync(""""
        using Dapper;
        using System.Data.Common;

        [DapperAot]
        static class Q
        {
            public static void ViaConst(DbConnection c) =>
                c.Query<int>(Sql.GetUsers, {|#1:new { Wrong = 1 }|});
        }
        """", DefaultConfig, [
            Diagnostic(Diagnostics.VariableNotDeclared).WithLocation(2).WithArguments("@MinLogins"),
            Diagnostic(Diagnostics.SqlParametersNotDetected).WithLocation(1),
    ], additionalSources: [SqlClass]);

    [Fact] // const sql in the same doc keeps its declaration token, https://github.com/DapperLib/DapperAOT/issues/177
    public Task ConstSqlInSameDocument() => CSVerifyAsync(""""
        using Dapper;
        using System.Data.Common;

        [DapperAot]
        static class Q
        {
            public const string GetUsers =
                "select Id from Users where LoginCount >= {|#0:@MinLogins|}";

            public static void ViaConst(DbConnection c) =>
                c.Query<int>(GetUsers, {|#1:new { Wrong = 1 }|});
        }
        """", DefaultConfig, [
            Diagnostic(Diagnostics.VariableNotDeclared).WithLocation(0).WithArguments("@MinLogins"),
            Diagnostic(Diagnostics.SqlParametersNotDetected).WithLocation(1),
    ]);
}
