using Dapper.CodeAnalysis;
using Dapper.Internal;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Xunit;

namespace Dapper.AOT.Test;

/// <summary>
/// Derives the gap table rather than asserting it: every public entry point on Dapper's
/// <c>SqlMapper</c> is classified by the same code the generator uses, and the result is compared
/// against a checked-in report. Two things this buys — the statuses cannot quietly rot, and an
/// overload added upstream shows up as a failure rather than as silence.
/// </summary>
/// <remarks>
/// The dispatch decision is a property of the method symbol alone (see
/// <see cref="Inspection.IsDapperMethod(IMethodSymbol?, out OperationFlags)"/>), so no call-site
/// needs synthesising. That also bounds what this can tell you: it reports what happens to an
/// <i>overload</i>, not to every call of it — a supported overload can still be refused at a
/// particular call-site for reasons of its own (an unconstructable result type, a type that is
/// generic by containment, and so on). Those refusals are diagnosed; see the interceptor
/// fixtures. Behavioural fidelity is a third question again, and only the Dapper test suite
/// answers it.
/// </remarks>
public class ApiSurfaceCoverageTests : GeneratorTestBase
{
    public ApiSurfaceCoverageTests(ITestOutputHelper log) : base(log) { }

    internal const string ReportFileName = "ApiSurface.expected.txt";

    [Fact]
    public void DapperPublicSurfaceIsClassifiedAndUnchanged()
    {
        var actual = BuildReport();
        var expectedPath = ReportFileName; // copied next to the test assembly
        var expected = File.Exists(expectedPath) ? File.ReadAllText(expectedPath) : "";

        if (!string.Equals(Normalize(expected), Normalize(actual), StringComparison.Ordinal))
        {
            var actualPath = Path.GetFullPath("ApiSurface.actual.txt");
            File.WriteAllText(actualPath, actual);
            Log($"surface report changed; new content written to {actualPath}");
            Log("if the change is expected, copy it over test/Dapper.AOT.Test/" + ReportFileName);
        }

        Assert.Equal(Normalize(expected), Normalize(actual));
    }

    private static string Normalize(string value) => value.Replace("\r\n", "\n").Trim();

    private string BuildReport()
    {
        // an empty compilation is enough: we only need Dapper's symbols, not a call-site
        var result = Execute<DapperInterceptorGenerator>("class Empty {}");
        var compilation = result.Compilation;
        Assert.NotNull(compilation);

        var sqlMapper = compilation!.GetTypeByMetadataName("Dapper.SqlMapper");
        Assert.NotNull(sqlMapper);

        var rows = new List<(string Disposition, string Signature)>();
        foreach (var method in sqlMapper!.GetMembers().OfType<IMethodSymbol>())
        {
            if (method.DeclaredAccessibility != Accessibility.Public || !method.IsStatic) continue;
            if (!method.IsExtensionMethod) continue;

            rows.Add((Classify(method), Describe(method)));
        }

        var sb = new StringBuilder();
        sb.Append("""
            # Dapper public surface, as Dapper.AOT sees it

            Generated by ApiSurfaceCoverageTests - do not hand-edit; run the test and copy the
            file it writes. Regenerate deliberately, and review the diff: a row moving to
            'skipped silently' is a bug, and a row appearing at all means Dapper added an API.

            Dispositions:
              candidate                     the generator attempts this overload; whether a given
                                            call-site is intercepted still depends on that
                                            call-site's own shapes
              unsupported API (diagnosed)   refused, and DAP001 names the method, so a consumer
                                            can see it
              unsupported API (undiagnosed) refused, but nothing says so
              not inspected                 outside the generator's name filter, so never
                                            examined - correct for helpers that need no
                                            interception, and worth checking nothing real is here
              unsupported: CommandDefinition
                                            the operation is supported, but not in this
                                            spelling: the SQL lives inside the struct, where
                                            build-time inspection cannot reach it. Reported by
                                            the generator as DAP057 (a warning when the project
                                            publishes native AOT, info otherwise)
              skipped silently              dropped with nothing reported - the consumer gets
                                            vanilla Dapper under JIT and a runtime failure under
                                            native AOT, with no build-time signal. Every row here
                                            is a defect
              non-goal: Type-based          refused on purpose, with DAP056: the row type comes
                                            from a Type at execution time, which generation
                                            cannot follow. Use the generic overload

            """.Replace("\r\n", "\n"));

        foreach (var group in rows.GroupBy(r => r.Disposition).OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            // distinct: an overload can appear more than once where only the `this` type differs
            // (IDbConnection vs DbConnection), which is not a distinction worth reporting
            var signatures = group.Select(r => r.Signature).Distinct(StringComparer.Ordinal)
                .OrderBy(x => x, StringComparer.Ordinal).ToList();
            sb.Append("\n## ").Append(group.Key).Append(" (").Append(signatures.Count).Append(")\n\n");
            foreach (var sig in signatures)
            {
                sb.Append("  ").Append(sig).Append('\n');
            }
        }
        return sb.ToString();
    }

    private static string Classify(IMethodSymbol method)
    {
        if (!Inspection.IsDapperMethod(method, out var flags)) return "not a Dapper operation";

        // the generator's syntax pre-filter is by method name, so anything outside it is never
        // examined at all - which is right for the helpers that need no interception
        if (!DapperInterceptorGenerator.IsCandidate(method.Name)) return "not inspected";

        // a *required* Type parameter means every call defers the row type to execution time,
        // which is a declared non-goal (DAP056). An optional one - GetRowParser<T>'s
        // concreteType - cannot be judged from the symbol: it depends on whether the call
        // passes it, so those stay in whichever bucket they would otherwise fall into
        foreach (var p in method.Parameters.Skip(1))
        {
            var pt = p.Type is IArrayTypeSymbol array ? array.ElementType : p.Type;
            if (!p.IsOptional
                && pt is { Name: "Type", ContainingNamespace: { Name: "System", ContainingNamespace.IsGlobalNamespace: true } })
            {
                return "non-goal: Type-based";
            }
        }

        // the analyzer only inspects (and so only reports on) call-sites carrying SQL as a
        // string argument. An overload that hides it inside CommandDefinition is invisible to
        // it - so the *generator* reports those instead, and neither is mute any more
        var visible = DapperInterceptorGenerator.IsVisibleToAnalyzer(method);
        if (flags.HasAny(OperationFlags.NotAotSupported))
        {
            // DAP001 either way: from the analyzer when it can see the call, from the generator
            // when it cannot
            return "unsupported API (diagnosed)";
        }
        if (visible) return "candidate";
        if (TakesCommandDefinition(method)) return "unsupported: CommandDefinition";

        // invisible to the analyzer, not CommandDefinition-shaped, and supportable at some
        // call-sites but not others - only GetRowParser<T>(concreteType) reaches here, and what
        // it does depends on whether a given call passes the Type. A symbol cannot say
        return "skipped silently";
    }

    private static bool TakesCommandDefinition(IMethodSymbol method)
    {
        foreach (var p in method.Parameters)
        {
            if (p.Type is { Name: "CommandDefinition", ContainingNamespace.Name: "Dapper" }) return true;
        }
        return false;
    }

    private static string Describe(IMethodSymbol method)
    {
        var sb = new StringBuilder(method.Name);
        if (method.Arity != 0) sb.Append('<').Append(method.Arity).Append('>');
        sb.Append('(');
        // skip the `this` parameter: it is the connection/reader and never varies meaningfully
        var first = true;
        foreach (var p in method.Parameters.Skip(1))
        {
            if (!first) sb.Append(", ");
            first = false;
            sb.Append(p.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat));
        }
        return sb.Append(')').ToString();
    }
}
