name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # depth is needed for nbgv

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x
            8.0.x
          include-prerelease: true      

      - name: Build
        run: dotnet build test/Dapper.AOT.Test.Integration/Dapper.AOT.Test.Integration.csproj -c Debug --verbosity detailed

      - name: '[Debug] Check Files'
        run: ls -R

      - name: Integration Tests
        run: dotnet test test/Dapper.AOT.Test.Integration/Dapper.AOT.Test.Integration.csproj --no-build --verbosity normal -c Debug